/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RfGmap {
    }
}
declare global {
    interface HTMLRfGmapElement extends Components.RfGmap, HTMLStencilElement {
    }
    var HTMLRfGmapElement: {
        prototype: HTMLRfGmapElement;
        new (): HTMLRfGmapElement;
    };
    interface HTMLElementTagNameMap {
        "rf-gmap": HTMLRfGmapElement;
    }
}
declare namespace LocalJSX {
    interface RfGmap {
    }
    interface IntrinsicElements {
        "rf-gmap": RfGmap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-gmap": LocalJSX.RfGmap & JSXBase.HTMLAttributes<HTMLRfGmapElement>;
        }
    }
}
